package message_model

// When a customer clicks an ad that redirects to WhatsApp, this object is included in the messages object.
//
// The referral object can be included in the following types of message: text, location, contact, image, video, document, voice, and sticker.
type Referral struct {
	SourceUrl    string `json:"source_url"`    // The Meta URL that leads to the ad or post clicked by the customer. Opening this url takes you to the ad viewed by your customer.
	Source_type  string `json:"source_type"`   // The type of the ad’s source; ad or post.
	Source_id    string `json:"source_id"`     // Meta ID for an ad or a post.
	Headline     string `json:"headline"`      // Headline used in the ad or post.
	Body         string `json:"body"`          // Body for the ad or post.
	Media_type   string `json:"media_type"`    // Media present in the ad or post; image or video.
	ImageUrl     string `json:"image_url"`     // URL of the image, when media_type is an image.
	VideoUrl     string `json:"video_url"`     // URL of the video, when media_type is a video.
	ThumbnailUrl string `json:"thumbnail_url"` // URL for the thumbnail, when media_type is a video.
	CtwaClid     string `json:"ctwa_clid"`     // Click ID generated by Meta for ads that click to WhatsApp.
}
