package message_type_interactive_model

// Described at
//
// https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#action-object
type Action struct {
	Button            string        `json:"button,omitempty"`              // Required for list messages. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not. Maximum length: 20 characters.
	Buttons           *[]ButtonData `json:"buttons,omitempty"`             // Required for Reply Button Messages.
	Sections          *[]Section    `json:"sections,omitempty"`            // Required for List Messages and Multi-Product Messages. There is a minimum of 1 and maximum of 10.
	CatalogId         string        `json:"catalog_id,omitempty"`          // Required for Single-Product Messages and Multi-Product Messages. Unique identifier of the Facebook catalog linked to your WhatsApp Business Account. This ID can be retrieved via Commerce Manager.
	ProductRetailerId string        `json:"product_retailer_id,omitempty"` // Required for Single-Product Messages and Multi-Product Messages. Unique identifier of the product in a catalog. Maximum 100 characters for both Single-Product and Multi-Product messages. To get this ID, go to Commerce Manager, select your Facebook Business account, and you will see a list of shops connected to your account. Click the shop you want to use. On the left-side panel, click Catalog > Items, and find the item you want to mention. The ID for that item is displayed under the item's name.

	FlowMode           *FlowMode           `json:"flow_mode,omitempty"`            // Optional for Flows Messages. The current mode of the Flow, either draft or published.
	FlowMessageVersion *FlowMessageVersion `json:"flow_message_version,omitempty"` // Required for Flows Messages.
	FlowToken          string              `json:"flow_token,omitempty"`           // Required for Flows Messages. A token that is generated by the business to serve as an identifier.
	FlowId             string              `json:"flow_id,omitempty"`              // Required for Flows Messages. Unique identifier of the Flow provided by WhatsApp.
	FlowCta            string              `json:"flow_cta,omitempty"`             // Required for Flows Messages. Text on the CTA button, eg. "Signup". Maximum length: 20 characters (no emoji).
	FlowAction         *FlowAction         `json:"flow_action,omitempty"`          // Optional for Flows Messages. navigate or data_exchange. Use navigate to predefine the first screen as part of the message. Use data_exchange for advanced use-cases where the first screen is provided by your endpoint.
	FlowActionPayload  *FlowActionPayload  `json:"flow_action_payload,omitempty"`  // Optional for Flows Messages. Required only if flow_action is navigate.
}
