package message_type_interactive_model

type FlowData struct {
	FlowMode           *FlowMode          `json:"flow_mode,omitempty"`           // Optional for Flows Messages. The current mode of the Flow, either draft or published.
	FlowMessageVersion FlowMessageVersion `json:"flow_message_version"`          // Required for Flows Messages.
	FlowToken          string             `json:"flow_token,omitempty"`          // Required for Flows Messages. A token that is generated by the business to serve as an identifier.
	FlowID             string             `json:"flow_id,omitempty"`             // Required for Flows Messages. Unique identifier of the Flow provided by WhatsApp.
	FlowCta            string             `json:"flow_cta,omitempty"`            // Required for Flows Messages. Text on the CTA button, eg. "Signup". Maximum length: 20 characters (no emoji).
	FlowAction         *FlowAction        `json:"flow_action,omitempty"`         // Optional for Flows Messages. navigate or data_exchange. Use navigate to predefine the first screen as part of the message. Use data_exchange for advanced use-cases where the first screen is provided by your endpoint.
	FlowActionPayload  *FlowActionPayload `json:"flow_action_payload,omitempty"` // Optional for Flows Messages. Required only if flow_action is navigate.
}
